### ISSUE TITLE
Add "Skip" Transfiguration chance

### ISSUE THREAD

**Issue by Divineaspect** [MinerArcana/Transfiguration#3]
This should be added especially to blessed dust.

**Comment by SkySom** [comment]
Skip?

**Comment by Divineaspect** [comment]
don't transmute this, but pass on the transfiguration event unchanged

**Comment by SkySom** [comment]
Should this still "wait" the time it'd take to transmute it?

**Comment by SkySom** [comment]
Bless now has a 20% chance to skip at the "half" way point that'd it try to spread, Types and Recipes can now both define chance it's added.
